name: Deploy Frontend

on:
  push:
    branches:
      - "master"
    paths:
      - "frontend/betcoin/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node: '15.x'
      - name: Install dependencies
        working-directory: ./frontend/betcoin/
        run: |
          npm install -g yarn
          yarn install
          yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-center-1

      - name: Deploy to s3
        working-directory: ./frontend/betcoin/
        run: aws s3 sync ./out s3://${{ secrets.AWS_S3_BUCKET_NAME }}

      - name: Invalidate Cloudfront cache
        working-directory: ./frontend/betcoin/
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
